# sudo chmod 666 /var/run/docker.sock

language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t prasadrotti027/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true prasadrotti027/react-test npm test -- --coverage

after_success:
    - docker build -t prasadrotti027/multi-client9 ./client
    - docker build -t prasadrotti027/multi-nginx9 ./nginx
    - docker build -t prasadrotti027/multi-server9 ./server
    - docker build -t prasadrotti027/multi-worker9 ./worker
    # Login to dockerCLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push to docker
    - docker push prasadrotti027/multi-client9
    - docker push prasadrotti027/multi-nginx9
    - docker push prasadrotti027/multi-server9
    - docker push prasadrotti027/multi-worker9
